#!/usr/local/bin/python3
import sys, os

print("content-type: text/html\n\n")

message = "Hello there! I was generated by a CGI!"

replyhtml = """
<html>
<body>
<p>%s</p>
</body>
</html>
"""
print(replyhtml % message)